---
- name: Configure host.
  hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

    - name: Pre-purchase Mac Store Apps
      import_tasks: tasks/pre-purchase-apps.yml
      tags: ['mas']

  roles:
    - role: elliotweiser.osx-command-line-tools

    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']

    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']

    - role: geerlingguy.mac.mas
      when: mas_installed_apps
      tags: ['mas']

    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']

  tasks:
    - import_tasks: tasks/karabiner.yml
      when: configure_karabiner
      tags: ['karabiner']

    - import_tasks: tasks/mise.yml
      tags: ['mise']

    # - import_tasks: tasks/loosen-gatekeeper.yml
    #   when: configure_loosen_gatekeeper
    #   tags: ['loosen-gatekeeper', 'once-in-a-blue-moon']

    - import_tasks: tasks/osx/osx.yml
      when: configure_osx
      tags: ['osx']

    - import_tasks: tasks/dock.yml
      when: configure_dock and (dockitems_persist_apps is defined or dockitems_persist_others is defined)
      tags: ['dock']

    - import_tasks: tasks/autostart.yml
      when: configure_autostart
      tags: ['autostart']

    - import_tasks: tasks/share-services.yml
      when: share_services_enabled or share_services_disabled
      tags: ['share-services']

    - import_tasks: tasks/display-resolution.yml
      when: configure_better_display_mode_number > 0
      tags: ['display-resolution']

    - import_tasks: tasks/default-browser-firefox.yml
      when: configure_firefox_as_default
      tags: ['default-browser']

    - import_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']

    - import_tasks: tasks/sublime-text.yml
      when: configure_sublime
      tags: ['sublime-text', 'once-in-a-blue-moon']

    - name: Run post-provision task files in a block.
      tags: ['post']
      block:
        - name: Run configured post-provision ansible task files.
          include_tasks: "{{ outer_item }}"
          loop_control:
            loop_var: outer_item
          with_fileglob: "{{ post_provision_tasks | default(omit) }}"

    # Keep it at the end because it copies the public key to clipboard
    # and prints some useful URLs on the terminal
    - import_tasks: tasks/ssh.yml
      when: configure_ssh
      tags: ['ssh']
