version: 7
profiles: []
groups: []
configSync:
  parts: {}
hotkeys:
  toggle-window:
    - F20
  copy-current-path: []
  ctrl-c:
    - ⌘-C
  copy:
    - ⌘-Shift-C
    - Ctrl-Shift-C
  paste:
    - ⌘-V
    - ⌘-Shift-V
    - Ctrl-V
    - Ctrl-Shift-V
  clear:
    - ⌘-K
    - ⌘-L
  select-all:
    - ⌘-A
  zoom-in:
    - ⌘-=
    - ⌘-Shift-=
  zoom-out:
    - ⌘--
    - ⌘-Shift--
  reset-zoom:
    - ⌘-0
  home:
    - ⌘-Left
    - Home
  end:
    - ⌘-Right
    - End
  previous-word:
    - ⌥-Left
  next-word:
    - ⌥-Right
  delete-previous-word:
    - ⌥-Backspace
  delete-line:
    - ⌘-Backspace
  delete-next-word:
    - ⌥-Delete
  search:
    - ⌘-F
  pane-focus-all:
    - ⌘-Shift-I
  focus-all-tabs:
    - ⌘-⌥-Shift-I
  scroll-to-top:
    - Shift-PageUp
  scroll-page-up:
    - ⌥-PageUp
  scroll-up:
    - Ctrl-Shift-Up
  scroll-down:
    - Ctrl-Shift-Down
  scroll-page-down:
    - ⌥-PageDown
  scroll-to-bottom:
    - Shift-PageDown
  restart-telnet-session: []
  restart-ssh-session: []
  launch-winscp: []
  settings-tab:
    hotkeys:
      - - Ctrl-K
        - Ctrl-S
  serial:
    - Alt-K
  restart-serial-session: []
  new-tab:
    - ⌘-T
  new-window:
    - ⌘-N
  profile: {}
  profile-selectors: {}
  group-selectors: {}
  toggle-fullscreen:
    - Ctrl+⌘+F
  reopen-tab:
    - ⌘-Shift-T
  rename-tab:
    - F2
  next-tab:
    - Ctrl-Tab
  previous-tab:
    - Ctrl-Shift-Tab
  move-tab-left: []
  move-tab-right: []
  rearrange-panes: []
  tab-1:
    - Ctrl-1
  tab-2:
    - Ctrl-2
  tab-3:
    - Ctrl-3
  tab-4:
    - Ctrl-4
  tab-5:
    - Ctrl-5
  tab-6:
    - Ctrl-6
  tab-7:
    - Ctrl-7
  tab-8:
    - Ctrl-8
  tab-9:
    - Ctrl-9
  tab-10: []
  duplicate-tab: []
  restart-tab: []
  reconnect-tab: []
  disconnect-tab: []
  explode-tab:
    - ⌘-Shift-.
  combine-tabs:
    - ⌘-Shift-,
  tab-11: []
  tab-12: []
  tab-13: []
  tab-14: []
  tab-15: []
  tab-16: []
  tab-17: []
  tab-18: []
  tab-19: []
  tab-20: []
  split-right:
    - ⌘-Shift-D
  split-bottom:
    - ⌘-D
  split-left: []
  split-top: []
  pane-nav-right:
    - ⌘-⌥-Right
  pane-nav-down:
    - ⌘-⌥-Down
  pane-nav-up:
    - ⌘-⌥-Up
  pane-nav-left:
    - ⌘-⌥-Left
  pane-nav-previous:
    - ⌘-⌥-[
  pane-nav-next:
    - ⌘-⌥-]
  pane-nav-1: []
  pane-nav-2: []
  pane-nav-3: []
  pane-nav-4: []
  pane-nav-5: []
  pane-nav-6: []
  pane-nav-7: []
  pane-nav-8: []
  pane-nav-9: []
  pane-maximize:
    - ⌘-⌥-Enter
  close-pane:
    - ⌘-Shift-W
  pane-increase-vertical: []
  pane-decrease-vertical: []
  pane-increase-horizontal: []
  pane-decrease-horizontal: []
  profile-selector:
    - ⌘-E
  switch-profile:
    - ⌘-Shift-E
  command-selector:
    - ⌘-Shift-P
  settings:
    - ⌘-,
    - Ctrl-,
  toggle-last-tab: []
  close-tab:
    - ⌘-W
terminal:
  searchOptions: {}
  colorScheme:
    name: Casalberto
    foreground: '#f2f2f2'
    background: '#050A11'
    cursor: '#4d4d4d'
    colors:
      - '#2a2a2a'
      - '#ff0000'
      - '#79ff0f'
      - '#e7bf00'
      - '#396bd7'
      - '#b449be'
      - '#66ccff'
      - '#bbbbbb'
      - '#666666'
      - '#ff0080'
      - '#66ff66'
      - '#f3d64e'
      - '#709aed'
      - '#db67e6'
      - '#7adff2'
      - '#ffffff'
  copyOnSelect: true
  copyAsHTML: false
  showTabProfileIcon: true
  customColorSchemes:
    - name: Casalberto
      foreground: '#f2f2f2'
      background: '#050A11'
      cursor: '#4d4d4d'
      colors:
        - '#2a2a2a'
        - '#ff0000'
        - '#79ff0f'
        - '#e7bf00'
        - '#396bd7'
        - '#b449be'
        - '#66ccff'
        - '#bbbbbb'
        - '#666666'
        - '#ff0080'
        - '#66ff66'
        - '#f3d64e'
        - '#709aed'
        - '#db67e6'
        - '#7adff2'
        - '#ffffff'
  cursor: beam
  font: FiraCode Nerd Font
  warnOnMultilinePaste: false
ssh: {}
clickableLinks: {}
accessibility:
  animations: false
appearance:
  tabsLocation: left
  dock: bottom
  tabsInFullscreen: true
  dockAlwaysOnTop: false
  dockHideOnBlur: true
  dockSpace: 0.93
hacks: {}
providerBlacklist: []
commandBlacklist: []
enableWelcomeTab: false
pluginBlacklist: []
profileDefaults:
  ssh:
    disableDynamicTitle: true
profileBlacklist: []
enableAnalytics: false
