---
- name: Get list of apps starting automatically with the system
  ansible.builtin.shell: "sudo sfltool dumpbtm | grep file://"
  register: sfltool_output
  changed_when: false

- name: Print apps starting automatically with the system
  ansible.builtin.debug:
    var: sfltool_output.stdout

- name: Remove autostart applications
  ansible.builtin.command: |
    osascript -e 'tell application "System Events" to delete login items whose name contains "{{ item }}"'
  loop: "{{ configure_autostart_avoid }}"
  when: configure_autostart_avoid is defined and item in sfltool_output.stdout

- name: Set autostart applications
  ansible.builtin.command: |
    osascript -e 'tell application "System Events" to make login item at end with properties {path:"{{ item }}", hidden:false}'
  loop: "{{ configure_autostart }}"
  when: configure_autostart is defined and item not in sfltool_output.stdout
