---
- name: Get list of apps starting automatically with the system
  ansible.builtin.shell: "sudo sfltool dumpbtm | grep file://"
  register: sfltool_output
  changed_when: false

- name: Print apps starting automatically with the system
  ansible.builtin.debug:
    var: sfltool_output.stdout

- name: Set autostart applications
  ansible.builtin.command: |
    osascript -e 'tell application "System Events" to make login item at end with properties {path:"{{ item }}", hidden:false}'
  loop: "{{ configure_autostart }}"
  when: item not in sfltool_output.stdout
