---
- name: Get default browser
  ansible.builtin.shell: |
    defaults read ~/Library/Preferences/com.apple.LaunchServices/com.apple.launchservices.secure | awk -F'"' '/http;/{print window[(NR)-1]}{window[NR]=$2}'
  register: default_browser
  changed_when: false
  failed_when: false

- name: Debug default browser
  ansible.builtin.debug:
    var: default_browser.stdout

- name: Set Firefox as default browser
  ansible.builtin.command: |
    open -a "Firefox" --new --args -silent -nosplash -setDefaultBrowser
  when: configure_firefox_as_default and 'firefox' not in default_browser.stdout
