---
- name: Get default browser
  ansible.builtin.shell: |
    defaults read ~/Library/Preferences/com.apple.LaunchServices/com.apple.launchservices.secure | awk -F'"' '/http;/{print window[(NR)-1]}{window[NR]=$2}'
  register: default_browser
  changed_when: false

- name: Debug default browser
  ansible.builtin.debug:
    var: default_browser.stdout

- name: Set Firefox as default browser
  ansible.builtin.command: |
    open -a "Firefox" --new --args -silent -nosplash -setDefaultBrowser
  when: configure_firefox_as_default and 'firefox' not in default_browser.stdout

# To allow unsigned apps choose Anywhere under System Preferences: Security: Allow apps downloaded from. If you don't have the option to select Anywhere you'll have to loosen the Gate Keeper restrictions by running sudo spctl --master-disable in the Terminal
# sudo spctl --master-disable
# Then, go to System Preferences > Privacy & Security > (Scroll down to Security section) > Allow applications from: Anywhere
# to undo: sudo spctl --master-enable
