---
- name: Check BetterDisplay is open
  command:
    cmd: ps -ax | grep -v grep | grep BetterDisplay
  register: betterdisplay_is_open
  changed_when: false
  failed_when: false

- name: Ensure BetterDisplay is open
  command:
    cmd: open /Applications/BetterDisplay.app
  register: display_mode_number
  changed_when: false
  when: betterdisplay_is_open.rc != 0

- when: betterdisplay_is_open.rc != 0
  pause:
    seconds: 2

- name: Get display mode number (it's kind of a multiplicator)
  command: betterdisplaycli get -name="Built-in Display" -displaymodenumber
  register: display_mode_number
  changed_when: false

- name: Debug display mode number
  ansible.builtin.debug:
    var: display_mode_number.stdout

- name: Set display mode
  command: betterdisplaycli set -name="Built-in Display" -displaymodenumber={{ configure_better_display_mode_number }}
  when: configure_better_display_mode_number > 0 and display_mode_number.stdout != configure_better_display_mode_number

- name: Get display mode number (for the 2nd display)
  command: betterdisplaycli get -name="SAMSUNG" -displaymodenumber
  register: second_display_mode_number
  changed_when: false
  ignore_errors: true

- name: Debug display mode number
  ansible.builtin.debug:
    var: second_display_mode_number.stdout
  when: second_display_mode_number.rc == 0

- name: Set display mode
  command: betterdisplaycli set -name="SAMSUNG" -displaymodenumber=122
  when: second_display_mode_number.rc == 0 and second_display_mode_number.stdout != "122"

# default: -displaymodenumber=54
