---
- name: Check if mise is installed
  command: which mise
  register: mise_check
  failed_when: false
  changed_when: false

- debug: var=mise_check

- name: Install mise environments
  command: mise install
  when: mise_check.rc == 0
