---
- name: Run ansible-role-oh-my-zsh.
  include_role:
    name: "ansible-role-oh-my-zsh"
  vars:
    omz_user: "{{ item }}"
    omz_zshrc_create: "false"
    # omz_plugins:
    #   - "autojump"
    #   - "git"
  with_items: "{{ users }}"