---

###############################################################################
# Dock, Dashboard, and hot corners                                            #
###############################################################################

# - name: Wipe all (default) app icons from the Dock
#   # This is only really useful when setting up a new Mac, or if you don't use
#   # the Dock to launch apps.
#   community.general.osx_defaults:
#     domain: com.apple.dock
#     key: persistent-apps
#     type: array
#     value: []
