---

###############################################################################
# Mail                                                                        #
###############################################################################

# - name: Add the keyboard shortcut ⌘ + Enter to send an email in Mail.app
#   # This is a complex dict-add operation that might need special handling
#   command: defaults write com.apple.mail NSUserKeyEquivalents -dict-add "Send" "@\U21a9"

- name: Get DraftsViewerAttributes
  ansible.builtin.shell: defaults read com.apple.mail DraftsViewerAttributes
  register: drafts_viewer_attributes
  changed_when: false

- name: Display emails in threaded mode, sorted by date (oldest at the top)
  # This is a complex dict-add operation that might need special handling
  command: defaults write com.apple.mail DraftsViewerAttributes -dict-add "DisplayInThreadedMode" -string "yes"
  when: '"DisplayInThreadedMode = yes" not in drafts_viewer_attributes.stdout'

- name: Display emails in threaded mode, sorted by date (oldest at the top)
  # This is a complex dict-add operation that might need special handling
  command: defaults write com.apple.mail DraftsViewerAttributes -dict-add "SortedDescending" -string "yes"
  when: '"SortedDescending = yes" not in drafts_viewer_attributes.stdout'

- name: Display emails in threaded mode, sorted by date (oldest at the top)
  # This is a complex dict-add operation that might need special handling
  command: defaults write com.apple.mail DraftsViewerAttributes -dict-add "SortOrder" -string "received-date"
  when: '"SortOrder = \"received-date\"" not in drafts_viewer_attributes.stdout'
