---

- name: Run "tasks/osx-*.yml" files.
  include_tasks: "{{ task_to_include }}"
  with_fileglob: "tasks/osx-*.yml"
  loop_control:
    loop_var: task_to_include

- name: Remove quarantine attributes from files
  include_tasks: "tasks/block-remove-quarantine.yml"
  loop: "{{ remove_quarantine }}"
  when: remove_quarantine is defined

- name: Set defaults
  command: "bash files/osx/.osx_defaults"
  changed_when: false

- name: Set defaults that require sudo
  command: "bash files/osx/.osx_defaults_sudo"
  changed_when: false
  become: true

# Ignore this by including the flag:
# --skip-tags once-in-a-blue-moon
- name: Run other commands
  command: "bash files/osx/.osx_delicate"
  changed_when: false
  become: true
  tags: ['once-in-a-blue-moon']

# Ignore this by including the flag:
# --skip-tags once-in-a-blue-moon
- name: Run destructive commands
  command: "bash files/osx/.osx_destructive"
  changed_when: false
  become: true
  tags: ['once-in-a-blue-moon']
