---
- name: Get list of apps from Settings > General > Login items & extensions > Sharing
  ansible.builtin.shell: "pluginkit -m -A -D -p com.apple.share-services"
  register: pluginkit_output
  changed_when: false

- name: Debug share services
  ansible.builtin.debug:
    var: pluginkit_output.stdout

- name: pluginkit disable
  ansible.builtin.command: |
    pluginkit -e ignore -i {{ item }}
  loop: "{{ share_services_disabled }}"
  when: "'-    ' + item not in pluginkit_output.stdout"

- name: pluginkit enable
  ansible.builtin.command: |
    pluginkit -e use -i {{ item }}
  loop: "{{ share_services_enabled }}"
  when: "'+    ' + item not in pluginkit_output.stdout"
