---

- name: "Ensure {{ item }} exists"
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop: "{{ ensure_directories_exist }}"

- name: Set icons to folders
  include_tasks: "tasks/osx/block-folder-icons.yml"
  when: folder_icons is defined
  loop: "{{ folder_icons }}"
